### ISSUE TITLE
Convert opaque PNGs to JPGs

### ISSUE THREAD

**Issue by BertrandBordage** [wagtail/Willow#66]
For optimisation, it would great to remove the alpha channel of PNGs when it contains only opaque pixels, and convert the image to JPG instead of PNG. It will generate a 1080p image of around 400 kB in JPG vs 2.2 MB for transparent PNG.

For those afraid of loosing quality in the PNG→JPG conversion, we can at least remove the alpha channel while keeping the PNG format.

Personally, I’m in favor of the PNG→JPG conversion for opaque images, because it makes sites load up to 5× faster with no visible difference (given the JPEG quality used by Willow).

**Comment by gasman** [comment]
No automatic PNG -> JPG conversion, please! It's a classic case of software that thinks it knows better than its users, instead of doing what you tell it to do. (IIRC, Twitter does the same thing, and it's a common hack to insert a single transparent pixel into an otherwise opaque image in order to override its behaviour. Let's not force our users to do that.)

**Comment by BertrandBordage** [comment]
Some users can do the single pixel trick if they want, but most users are not aware that their photos may contain a transparency channel. So what’s the point of serving an empty fourth channel?

About the type conversion, I meant the conversion should be done on cropped/resized images, not on original ones. It could be disabled using an argument of the Wagtail image tools (template tag & Jinja2 function). Honestly, I’m curious to know what’s the downside of it since the image is not the original one?

**Comment by BertrandBordage** [comment]
There’s also a speed argument I forgot to mention: most PNG encoders are outrageously slower than JPG encoders. In our case, on Pillow, saving a 1080p PNG is ≈7× slower than for the equivalent JPG.
In some Wagtail sites, it is a major slowdown of the image gallery after importing a bunch of images.

**Comment by gasman** [comment]
If the transparency channel is empty, then it will compress to practically nothing.

I've worked with enough non-photographic images to know that there's no optimal quality setting that will reliably eliminate all visible JPEG artefacts (other than setting it to 100% / lossless, at which point you've lost most of the benefit of using JPEG). Even if you achieve acceptable quality 99% of the time, degrading images the other 1% of the time, due to a conversion that you didn't request or want, isn't really forgivable. I'd count it in the same category as Excel having "creative" interpretations of certain string formats... some people might like the convenience and friendliness, but if it interferes with our ability to _reliably_ do the fundamental data processing task we were supposed to be doing, it's not a good thing :-)

**Comment by BertrandBordage** [comment]
It’s not entirely true. Let me show you with an example RGBA file resized by Wagtail, and therefore Willow: [table.fill-1920x1080.png](https://user-images.githubusercontent.com/1119169/41809267-f28efde4-76ea-11e8-8f37-49dbed6eeb41.png)
This image’s size is **2 217 078 bytes**.
Let’s check its transparency channel:
```python
from PIL import Image

image = Image.open('table.fill-1920x1080.png')
print(image.getchannel('A').getcolors())  # Prints [(2070601, 255)]
```
It is indeed empty, all pixels having a 255/255 opacity.
Now let’s remove the alpha channel and save the image again as PNG:
```python
image = image.convert('RGB')
image.save('table.png')
```
And the size of the new file is **1 992 162 bytes**, which means the empty alpha channel weighs **224 916 bytes**, more than 10 % of the image. This is not 25 % of the image so it is indeed compressed, but that’s still ridiculous given that there could be a special single-byte metadata meaning “this channel is empty”.

And then when we save the image to 100% quality JPEG instead of PNG:
```python
image.save('table.jpg', quality=100)
```
We get an image of **983 841 bytes**, 44 % of the original file size. I know, this will not be true in some cases like palette and greyscale modes where PNG is more compressed. (By the way, we can also optimize by automatically switching to palette mode in opaque images with 256 colors or less)

I know there is still some invisible difference, as shown using ImageMagick’s `compare` and that the type comparison can still be discussed. But dropping empty channels is still a must have, decreasing size, conversion duration and probably RAM usage:
![image](https://user-images.githubusercontent.com/1119169/41809497-dbf57a28-76ee-11e8-9f71-2409b2953549.png)

Also, note that **Willow already degrades the quality of some images**, because JPEGs with a quality higher than 85% end up with a 85% quality.

Maybe this discussion needs to be split in separate issues, or be moved to Wagtail? I’m not sure whether we want optimizations to occur in Willow or Wagtail.

**Comment by BertrandBordage** [comment]
@kaedroho: do you think it would be right to close this issue and open one on Willow about removing empty alpha channels and another on Wagtail for PNG→JPEG when in RGB mode?

**Comment by kaedroho** [comment]
@BertrandBordage Sounds like a good idea to me

**Comment by BertrandBordage** [comment]
Closing this in favour of #67 and [wagtail/wagtail#4655](https://github.com/wagtail/wagtail/issues/4655)
